
import type React from 'react';
import type { AnalyzeNutritionOutput } from '@/ai/flows/nutrition-analysis';

interface PrintableNutritionReportProps {
  analysisResult: AnalyzeNutritionOutput;
  userInput?: { servingSize?: string | undefined; [key: string]: any }; // To display what user entered
}

export const PrintableNutritionReport: React.FC<PrintableNutritionReportProps> = ({ analysisResult, userInput }) => {
  const styles: { [key: string]: React.CSSProperties } = {
    page: { padding: '40px', fontFamily: 'Arial, sans-serif', fontSize: '10pt', lineHeight: '1.5', color: '#333', width: '210mm', boxSizing: 'border-box' },
    companyHeader: { textAlign: 'center', fontSize: '16pt', fontWeight: 'bold', marginBottom: '10px', color: '#0f172a' },
    reportTitle: { textAlign: 'center', fontSize: '14pt', fontWeight: 'bold', marginBottom: '20px', color: '#10b981' },
    sectionTitle: { fontSize: '12pt', fontWeight: 'bold', marginTop: '20px', marginBottom: '10px', borderBottom: '1px solid #ccc', paddingBottom: '5px', color: '#0f172a' },
    subTitle: { fontSize: '11pt', fontWeight: 'bold', marginTop: '15px', marginBottom: '5px' },
    paragraph: { marginBottom: '10px' },
    ratingBlock: { border: '1px solid #eee', padding: '10px', borderRadius: '5px', marginBottom: '10px', backgroundColor: '#f9f9f9' },
    ratingTitle: { fontWeight: 'bold', marginBottom: '3px' },
    ratingValue: { fontSize: '10pt' },
     footer: { marginTop: '30px', paddingTop: '10px', borderTop: '1px solid #ccc', fontSize: '8pt', textAlign: 'center' as 'center', color: '#777'}
  };

  return (
    <div style={styles.page}>
      <div style={styles.companyHeader}>Swasth Bharat Advisor</div>
      <div style={styles.reportTitle}>AI Nutrition Analysis</div>

      {userInput?.servingSize && (
        <div style={styles.paragraph}><strong>Serving Size Context:</strong> {userInput.servingSize}</div>
      )}
      
      <div style={styles.sectionTitle}>Overall Assessment</div>
      <div style={styles.ratingBlock}>
        <div style={styles.ratingTitle}>Nutrition Density Rating:</div>
        <div style={styles.ratingValue}>{analysisResult.nutritionDensityRating}/5 stars</div>
      </div>
      <div style={styles.subTitle}>Overall Analysis:</div>
      <p style={styles.paragraph}>{analysisResult.overallAnalysis}</p>

      {analysisResult.macronutrientBalance && (
        <>
          <div style={styles.subTitle}>Macronutrient Balance:</div>
          <p style={styles.paragraph}>{analysisResult.macronutrientBalance}</p>
        </>
      )}
      {analysisResult.micronutrientHighlights && (
        <>
          <div style={styles.subTitle}>Micronutrient Highlights:</div>
          <p style={styles.paragraph}>{analysisResult.micronutrientHighlights}</p>
        </>
      )}
      {analysisResult.processingLevelAssessment && (
        <>
          <div style={styles.subTitle}>Processing Level Assessment:</div>
          <p style={styles.paragraph}>{analysisResult.processingLevelAssessment}</p>
        </>
      )}
      
      <div style={styles.sectionTitle}>Dietary Suitability</div>
      <p style={styles.paragraph}>{analysisResult.dietarySuitability}</p>

      {analysisResult.servingSizeContext && (
        <>
          <div style={styles.subTitle}>Comments on Serving Size:</div>
          <p style={styles.paragraph}>{analysisResult.servingSizeContext}</p>
        </>
      )}
      <div style={styles.footer}>
        Generated by Swasth Bharat Advisor | Page <span className="pageNumber"></span> of <span className="totalPages"></span> <br/>
        Disclaimer: This AI analysis is for informational purposes only and not a substitute for professional medical or dietary advice.
      </div>
    </div>
  );
};
